package loan

import org.gsoft.openserv.domain.loan.Loan
import org.gsoft.openserv.rulesengine.event.LoanTemporalEvent
import org.springframework.context.ApplicationContext
import org.gsoft.openserv.buslogic.interest.LoanInterestRateFactory

global ApplicationContext springContext

rule "Update Loan Interest Rate"
	when
		$l : Loan(effectiveLoanTypeProfile  != null, servicingStartDate != null, effectiveLoanTypeProfile.baseRateUpdateFrequency != null)
		not LoanInterestRateUpdated(loanId == $l.loanID)
	then
		System.out.println("Updating Interest Rate");
		springContext.getBean(LoanInterestRateFactory.class).setRateForLoan($l);
		LoanInterestRateUpdated liru = new LoanInterestRateUpdated();
		liru.setLoanId($l.getLoanID());
		insert(liru);
end