package loan

import org.gsoft.openserv.domain.loan.LoanType
import org.gsoft.openserv.domain.loan.LoanTypeProfile
import org.gsoft.openserv.rulesengine.event.LoanTypeChangedEvent
import org.gsoft.openserv.rulesengine.event.LoanTypeProfileChangedEvent
import java.util.List
import org.gsoft.openserv.repositories.loan.LoanRepository;

global ApplicationContext springContext

rule "Load Loans on LoanType change"
	when
		LoanTypeChangedEvent($lt:loanType)
	then
		System.out.println("Loading Loans based on loan type");
		List loans = springContext.getBean(LoanRepository.class).findAllByLoanType($lt);
		for(Object loan:loans){
			insert(loan);
		}
end

rule "Load Loans on LoanTypeProfile change"
	when
		LoanTypeProfileChangedEvent($lt:loanTypeProfile.loanType)
	then
		System.out.println("Loading Loans based on loan type");
		List loans = springContext.getBean(LoanRepository.class).findAllByLoanType($lt);
		for(Object loan:loans){
			insert(loan);
		}
end
