package loan

import org.gsoft.openserv.domain.loan.Loan
import org.springframework.context.ApplicationContext
import org.gsoft.openserv.buslogic.account.AccountLogic
import java.util.Date
import java.util.Calendar

global ApplicationContext springContext

rule "Assign account number to loan"
	when
		$l : Loan(account == null, lenderID != null, loanProgram != null)
	then
		$l = springContext.getBean(AccountLogic.class).addLoanToAccount($l);
		update($l);
end