import org.gsoft.openserv.domain.loan.Loan
import org.springframework.context.ApplicationContext
import org.gsoft.openserv.buslogic.repayment.ServicingStartDateCalculator
rule "Update Servicing Start Date" 
when
	$l : Loan(servicingStartDate == null)
	$ac : ApplicationContext();
then
	System.out.println("set the servicing start date");
	$ac.getBean(ServicingStartDateCalculator.class).updateServicingStartDate($l);
end
